steps:
- name: node:20.0.0
  entrypoint: npm
  args: ["install"]
- name: node:20.0.0
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'REACT_APP_CLIENT_URL=${_CLIENT_URL}'
    - 'REACT_APP_X_SERVICE_URL=${_X_SERVICE_URL}'
    - 'REACT_APP_RUN_SERVICE_URL=${_RUN_SERVICE_URL}'
    - 'REACT_APP_GOOGLE_CLIENT_ID=${_GOOGLE_CLIENT_ID}'
    - 'REACT_APP_GITHUB_CLIENT_ID=${_GITHUB_CLIENT_ID}'
- name: node:20.0.0
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", "${_CONFIG_FILE}"]
timeout: "1600s"
options:
  logging: CLOUD_LOGGING_ONLY